name: Lab 1 Exercise Compile Runner
run-name: ${{ github.actor }}
on: push
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y \
          g++-11 
      - name: Compile 
        run: g++-11 -std=c++20 -Wall -Wextra -Wpedantic -Wconversion main.cpp

